export enum UI_EVENT {
    NAV_COLLAPSE = "NAV-COLLAPSE",
    UPDATE_CONTRACT_TABLE_LIST = "UPDATE-CONTRACT-TABLE-LIST",
    UPDATE_KPI_FILTER = "UPDATE_KPI_FILTER",
    UPDATE_ROLE = "UPDATE_ROLE",
}